# Generated by Django 2.2 on 2020-10-09 03:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authors',
            name='notes',
            field=models.CharField(default="They're good.", max_length=255),
            preserve_default=False,
        ),
    ]
