# Generated by Django 2.2 on 2020-10-10 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books_authors_app', '0002_authors_notes'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='authors',
            new_name='author',
        ),
    ]
